"use client";
import { useState } from "react";
import { DashboardPage } from "@makyschool/ui/components/layout/DashboardPage";
import { LoadingButton } from "@makyschool/ui/components/ui/LoadingButton";
import { olevelApi } from "@/lib/api/olevel";
import { useOLevelClasses, useOLevelCurriculum, useOLevelExamSessions, useOLevelSubmissions, useOLevelTerms } from "@/hooks/useOLevel";
import { useToast } from "@/providers/ToastProvider";
export function OLevelExamSessionsContent() {
 const {toast}=useToast(); const {data:curriculum}=useOLevelCurriculum(); const {data:classes=[]}=useOLevelClasses(); const {data:terms=[]}=useOLevelTerms(); const [classId,setClassId]=useState(""); const [termId,setTermId]=useState(""); const [status,setStatus]=useState(""); const [selected,setSelected]=useState(""); const {data:sessions=[],refetch}=useOLevelExamSessions({classId,termId,status}); const {data:submissions=[]}=useOLevelSubmissions(selected); const [creating,setCreating]=useState(false);
 const selectedTerm=terms.find(t=>t.id===termId)??terms.find(t=>t.isCurrent);
 async function create(form:HTMLFormElement){const data=new FormData(form); if(!curriculum||!selectedTerm)return toast.error("Choose a term and set up curriculum."); setCreating(true);try{await olevelApi.createExamSession({curriculumId:curriculum.id,classId:String(data.get("classId")),termId:selectedTerm.id,academicYearId:selectedTerm.academicYearId,categoryId:String(data.get("categoryId")),title:String(data.get("title")),maxMarks:Number(data.get("maxMarks"))});toast.success("Exam session created.");form.reset();await refetch();}catch(e){toast.error(e instanceof Error?e.message:"Could not create session.");}finally{setCreating(false);}}
 return <DashboardPage embedded maxWidth="7xl" eyebrow="O-Level" title="Exam sessions"><div className="space-y-5"><div className="grid gap-3 rounded-xl border border-theme bg-theme-surface p-4 md:grid-cols-4"><select className="ms-input" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">All classes</option>{classes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select className="ms-input" value={termId} onChange={e=>setTermId(e.target.value)}><option value="">All terms</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name} · {t.academicYearName}</option>)}</select><select className="ms-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>draft</option><option>open</option><option>closed</option></select></div>
 <form className="grid gap-3 rounded-xl border border-theme bg-theme-surface p-4 md:grid-cols-5" onSubmit={e=>{e.preventDefault();void create(e.currentTarget)}}><select className="ms-input" name="classId" required><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="ms-input" name="title" required placeholder="Session title"/><select className="ms-input" name="categoryId" required><option value="">Category</option>{curriculum?.assessmentCategories?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="ms-input" name="maxMarks" type="number" defaultValue="100"/><LoadingButton loading={creating}>Create session</LoadingButton></form>
 <div className="overflow-x-auto rounded-xl border border-theme bg-theme-surface"><table className="min-w-full text-sm"><thead className="text-xs text-theme-muted"><tr><th className="p-3 text-left">Session</th><th>Class</th><th>Term</th><th>Status</th><th>Actions</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id} className="border-t border-theme"><td className="p-3">{s.title}<div className="text-xs text-theme-muted">{s.categoryName} · /{s.maxMarks}</div></td><td>{s.className}</td><td>{s.termName}</td><td><span className="rounded-full bg-theme-raised px-2 py-1 text-xs">{s.status}</span></td><td className="space-x-2"><button className="text-theme-accent" onClick={()=>setSelected(s.id)}>Submissions</button>{s.status==="draft"&&<button onClick={async()=>{if(confirm("Open this session?")){await olevelApi.openExamSession(s.id);void refetch();}}}>Open</button>}{s.status==="open"&&<button onClick={async()=>{if(confirm("Close this session?")){await olevelApi.closeExamSession(s.id);void refetch();}}}>Close</button>}</td></tr>)}</tbody></table></div>
 {selected&&<div className="rounded-xl border border-theme bg-theme-surface p-4"><h2 className="font-semibold">Subject submissions</h2>{submissions.map(x=><div key={x.id} className="flex justify-between border-t border-theme py-3 text-sm"><span>{x.subjectName} · {x.teacherName}</span><span>{x.enteredCount} entered · {x.status} {x.status==="submitted"&&<button className="ml-2 text-theme-accent" onClick={async()=>{const reason=prompt("Reason for unlock");if(reason){await olevelApi.unlockMarks(selected,{subjectId:x.subjectId,teacherId:x.teacherId,reason});toast.success("Marks unlocked.");}}}>Unlock</button>}</span></div>)}</div>}</div></DashboardPage>;
}
