"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { DashboardPage } from "@makyschool/ui/components/layout/DashboardPage";
import { LoadingButton } from "@makyschool/ui/components/ui/LoadingButton";
import { olevelApi } from "@/lib/api/olevel";
import { useOLevelClasses, useOLevelCurriculum, useOLevelCurriculumSubjects, useOLevelEnrollments, useOLevelTerms } from "@/hooks/useOLevel";
import { useToast } from "@/providers/ToastProvider";
export function OLevelStudentsContent() {
 const {toast}=useToast();const {data:classes=[]}=useOLevelClasses();const {data:terms=[]}=useOLevelTerms();const {data:curriculum}=useOLevelCurriculum();const [classId,setClassId]=useState("");const [yearId,setYearId]=useState("");const [selected,setSelected]=useState("");const {data:enrollments=[],refetch}=useOLevelEnrollments(classId,yearId);const {data:subjects=[]}=useOLevelCurriculumSubjects(curriculum?.id);const [busy,setBusy]=useState(false);
 const years=Array.from(new Map(terms.map(t=>[t.academicYearId,t.academicYearName])).entries());const selectedClass=classes.find(c=>c.id===classId);
 async function bulkEnroll(){if(!classId||!yearId||!curriculum)return toast.error("Select a class and academic year.");setBusy(true);try{const r=await olevelApi.bulkEnroll({classId,academicYearId:yearId,curriculumId:curriculum.id});toast.success(`${r.enrolled} students enrolled (${r.skipped} unchanged).`);void refetch();}catch(e){toast.error(e instanceof Error?e.message:"Enrollment failed.");}finally{setBusy(false);}}
 async function registerCompulsory(){if(!classId||!yearId)return toast.error("Select a class and academic year.");const list=subjects.filter(s=>s.subjectRole==="compulsory"&&(!selectedClass||s.appliesToLevels.includes(selectedClass.level))).map(s=>({subjectId:s.subjectId,subjectRole:"compulsory"}));try{await olevelApi.bulkRegisterSubjects({classId,academicYearId:yearId,subjects:list});toast.success("Compulsory subjects registered.");}catch(e){toast.error(e instanceof Error?e.message:"Registration failed.");}}
 return <DashboardPage embedded maxWidth="7xl" eyebrow="O-Level" title="Students and subject registration"><div className="space-y-5"><div className="flex flex-wrap gap-3 rounded-xl border border-theme bg-theme-surface p-4"><select className="ms-input" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Choose class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="ms-input" value={yearId} onChange={e=>setYearId(e.target.value)}><option value="">Academic year</option>{years.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><LoadingButton loading={busy} onClick={()=>void bulkEnroll()}>Bulk enroll class</LoadingButton><button className="rounded-lg bg-theme-raised px-3 py-2 text-sm" onClick={()=>void registerCompulsory()}>Register compulsory subjects</button></div>
 <div className="overflow-x-auto rounded-xl border border-theme bg-theme-surface"><table className="min-w-full text-sm"><thead className="text-xs text-theme-muted"><tr><th className="p-3 text-left">Student</th><th>Student ID</th><th>Class</th><th></th></tr></thead><tbody>{enrollments.map(e=><tr key={e.id} className="border-t border-theme"><td className="p-3">{e.studentName}</td><td>{e.learnerId??"—"}</td><td>{e.className}</td><td><button className="text-theme-accent" onClick={()=>setSelected(e.id)}>Subjects</button></td></tr>)}</tbody></table></div>
 {selected&&<RegistrationPanel enrollmentId={selected} subjects={subjects} yearId={yearId} onDone={()=>{setSelected("");toast.success("Subject registration saved.");}}/>}</div></DashboardPage>;
}
function RegistrationPanel({enrollmentId,subjects,yearId,onDone}:{enrollmentId:string;subjects:any[];yearId:string;onDone:()=>void}){const [chosen,setChosen]=useState<string[]>(subjects.filter(s=>s.subjectRole==="optional").map(s=>s.subjectId));const optional=subjects.filter(s=>s.subjectRole==="optional");const toggle=(id:string)=>setChosen(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);return <div className="rounded-xl border border-theme bg-theme-surface p-4"><h2 className="font-semibold">Optional subjects ({chosen.length} selected)</h2><p className="my-2 text-sm text-theme-muted">Choose optional subjects within the curriculum selection-rule limits.</p><div className="grid gap-2 sm:grid-cols-2">{optional.map(s=><label key={s.subjectId} className="flex gap-2 text-sm"><input type="checkbox" checked={chosen.includes(s.subjectId)} onChange={()=>toggle(s.subjectId)}/>{s.name} ({s.code})</label>)}</div><button className="mt-4 rounded-lg bg-theme-accent px-3 py-2 text-sm text-white" onClick={async()=>{await olevelApi.registerSubjects(enrollmentId,[...subjects.filter(s=>s.subjectRole==="compulsory").map(s=>({subjectId:s.subjectId,subjectRole:"compulsory"})),...chosen.map(subjectId=>({subjectId,subjectRole:"optional"}))]);onDone();}}>Save registration</button></div>;}
