"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { ChevronDown, Download } from "lucide-react";
import { DashboardPage } from "@makyschool/ui/components/layout/DashboardPage";
import { LoadingButton } from "@makyschool/ui/components/ui/LoadingButton";
import { olevelApi } from "@/lib/api/olevel";
import { useApproveOLevelResults, useGradeOLevelClass, useOLevelClassResults, useOLevelClasses, useOLevelTerms, useRankOLevelClass } from "@/hooks/useOLevel";
import { useToast } from "@/providers/ToastProvider";
export function OLevelResultsContent(){const {toast}=useToast();const {data:classes=[]}=useOLevelClasses();const {data:terms=[]}=useOLevelTerms();const current=terms.find(t=>t.isCurrent);const [classId,setClassId]=useState("");const [termId,setTermId]=useState(current?.id??"");const yearId=terms.find(t=>t.id===termId)?.academicYearId??"";const {data:results,refetch}=useOLevelClassResults(classId,termId,yearId);const grade=useGradeOLevelClass(),rank=useRankOLevelClass(),approve=useApproveOLevelResults();const [expanded,setExpanded]=useState<string|null>(null);const payload={classId,termId,academicYearId:yearId};async function run(fn:any,message:string){if(!classId||!termId)return toast.error("Choose class and term.");try{await fn.mutateAsync(payload);toast.success(message);void refetch();}catch(e){toast.error(e instanceof Error?e.message:"Action failed.");}}async function download(id:string){try{const blob=await olevelApi.downloadStudentReport(id,termId,yearId);const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="o-level-report.pdf";a.click();URL.revokeObjectURL(a.href);}catch(e){toast.error(e instanceof Error?e.message:"Download failed.");}}
return <DashboardPage embedded maxWidth="7xl" eyebrow="O-Level" title="Results"><div className="space-y-5"><div className="flex flex-wrap gap-3 rounded-xl border border-theme bg-theme-surface p-4"><select className="ms-input" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="ms-input" value={termId} onChange={e=>setTermId(e.target.value)}>{terms.map(t=><option key={t.id} value={t.id}>{t.name} · {t.academicYearName}</option>)}</select><LoadingButton loading={grade.isPending} onClick={()=>void run(grade,"Grading complete.")}>Run grading</LoadingButton><LoadingButton loading={rank.isPending} onClick={()=>void run(rank,"Rankings calculated.")}>Calculate rankings</LoadingButton><LoadingButton loading={approve.isPending} onClick={()=>void run(approve,"Results approved.")}>Approve</LoadingButton></div><div className="overflow-x-auto rounded-xl border border-theme bg-theme-surface"><table className="min-w-full text-sm"><thead className="text-xs text-theme-muted"><tr><th className="p-3 text-left">Position</th><th className="text-left">Student</th><th>Total points</th><th>Average</th><th>Promoted</th><th></th></tr></thead><tbody>{results?.students.map(r=><><tr key={r.id} className="border-t border-theme"><td className="p-3">{r.classPosition??"—"}/{r.totalStudentsInClass??"—"}</td><td>{r.studentName}<div className="text-xs text-theme-muted">{r.learnerId}</div></td><td>{r.totalPoints}</td><td>{r.averagePercent.toFixed(1)}%</td><td>{r.isPromoted===null?"—":r.isPromoted?"Yes":"No"}</td><td className="space-x-2"><button onClick={()=>setExpanded(expanded===r.id?null:r.id)}><ChevronDown className="inline h-4 w-4"/></button><button onClick={()=>void download(r.enrollmentId)}><Download className="inline h-4 w-4"/></button></td></tr>{expanded===r.id&&<tr key={`${r.id}-details`} className="border-t border-theme"><td colSpan={6} className="p-4"><div className="grid gap-2 sm:grid-cols-2">{r.subjectResults?.map(s=><div key={s.id} className="flex justify-between rounded bg-theme-raised px-3 py-2"><span>{s.subjectName} <small>{s.subjectCode}</small></span><span>{s.weightedScore.toFixed(1)}% · {s.grade} · {s.points}</span></div>)}</div></td></tr>}</>)}</tbody></table></div></div></DashboardPage>;}
