"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { DashboardPage } from "@makyschool/ui/components/layout/DashboardPage";
import { LoadingButton } from "@makyschool/ui/components/ui/LoadingButton";
import { olevelApi } from "@/lib/api/olevel";
import { useOLevelCurriculum, useOLevelMarkGrid, useSaveOLevelMarks, useSubmitOLevelMarks, useTeacherOLevelAssignments } from "@/hooks/useOLevel";
import { useToast } from "@/providers/ToastProvider";
export function TeacherOLevelMarksContent(){const params=useSearchParams();const {toast}=useToast();const {data:assignments=[]}=useTeacherOLevelAssignments();const [sessionId,setSessionId]=useState(params.get("session")??"");const [subjectId,setSubjectId]=useState(params.get("subject")??"");const assignment=assignments.find(a=>a.examSessionId===sessionId&&a.subjectId===subjectId);const {data:grid,refetch}=useOLevelMarkGrid(sessionId,subjectId);const {data:curriculum}=useOLevelCurriculum();const [marks,setMarks]=useState<any[]>([]);const save=useSaveOLevelMarks(),submit=useSubmitOLevelMarks();useEffect(()=>setMarks(grid?.marks??[]),[grid]);const grade=(score:number|null)=>{if(score===null||!grid)return "—";const percent=score/grid.examSession.maxMarks*100;const scale=grid.gradeScale??curriculum?.gradeScale??[];return scale.find(g=>percent>=g.minPercent&&percent<=g.maxPercent)?.grade??"—";};const locked=grid?.submissionStatus==="submitted";function update(i:number,key:string,value:any){setMarks(x=>x.map((m,n)=>n===i?{...m,[key]:value}:m));}async function persist(){try{await save.mutateAsync({examSessionId:sessionId,subjectId,marks:marks.map(m=>({studentId:m.studentId,rawScore:m.rawScore===""?null:Number(m.rawScore),isAbsent:m.isAbsent,remarks:m.remarks}))});toast.success("Draft saved.");void refetch();}catch(e){toast.error(e instanceof Error?e.message:"Could not save marks.");}}async function lock(){await persist();try{await submit.mutateAsync({examSessionId:sessionId,subjectId});toast.success("Marks submitted and locked.");void refetch();}catch(e){toast.error(e instanceof Error?e.message:"Could not submit marks.");}}
return <DashboardPage embedded maxWidth="7xl" eyebrow="O-Level" title="Enter marks"><div className="space-y-5"><select className="ms-input max-w-xl" value={`${sessionId}:${subjectId}`} onChange={e=>{const [s,sub]=e.target.value.split(":");setSessionId(s);setSubjectId(sub);}}><option value=":">Choose assignment</option>{assignments.map(a=><option key={`${a.examSessionId}:${a.subjectId}`} value={`${a.examSessionId}:${a.subjectId}`}>{a.subjectName} · {a.title} · {a.className}</option>)}</select>{grid&&<><div className="rounded-xl border border-theme bg-theme-surface p-4 text-sm"><b>{assignment?.subjectName}</b> · {grid.examSession.title} · maximum {grid.examSession.maxMarks} · <span className="text-theme-muted">{grid.submissionStatus}</span>{grid.submissionStatus==="unlocked"&&grid.unlockReason?<p className="mt-2 text-amber-700 dark:text-amber-300">Unlocked for correction: {grid.unlockReason}</p>:null}</div><div className="overflow-x-auto rounded-xl border border-theme bg-theme-surface"><table className="min-w-full text-sm"><thead className="text-xs text-theme-muted"><tr><th className="p-3 text-left">Student</th><th>Score</th><th>Absent</th><th>Remarks</th><th>Live % / grade</th></tr></thead><tbody>{marks.map((m,i)=>{const score=m.rawScore===null?null:Number(m.rawScore);const pct=score===null?"—":`${(score/grid.examSession.maxMarks*100).toFixed(1)}%`;return <tr key={m.studentId} className="border-t border-theme"><td className="p-3">{m.studentName}</td><td><input className="ms-input w-20" type="number" min="0" max={grid.examSession.maxMarks} disabled={locked} value={m.rawScore??""} onChange={e=>update(i,"rawScore",e.target.value)}/></td><td><input type="checkbox" checked={m.isAbsent} disabled={locked} onChange={e=>update(i,"isAbsent",e.target.checked)}/></td><td><input className="ms-input" disabled={locked} value={m.remarks??""} onChange={e=>update(i,"remarks",e.target.value)}/></td><td>{pct} · {grade(score)}</td></tr>})}</tbody></table></div>{!locked&&<div className="flex gap-3"><LoadingButton loading={save.isPending} onClick={()=>void persist()}>Save draft</LoadingButton><LoadingButton loading={submit.isPending} onClick={()=>void lock()}>Submit and lock</LoadingButton></div>}</>}</div></DashboardPage>;}
