services:
  makyschool-api:
    build: .
    container_name: makyschool-api-${ENV_NAME:-prod}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads